package com.example.romanovsky_m.testproject.Database;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PARAM_DB".
*/
public class ParamDBDao extends AbstractDao<ParamDB, Long> {

    public static final String TABLENAME = "PARAM_DB";

    /**
     * Properties of entity ParamDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ID = new Property(0, Long.class, "ID", true, "_id");
        public final static Property NAME = new Property(1, String.class, "NAME", false, "NAME");
        public final static Property VALUE = new Property(2, String.class, "VALUE", false, "VALUE");
        public final static Property OFFER_ID = new Property(3, Long.class, "OFFER_ID", false, "OFFER__ID");
    }

    private Query<ParamDB> offerDB_MParamsListQuery;

    public ParamDBDao(DaoConfig config) {
        super(config);
    }
    
    public ParamDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PARAM_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: ID
                "\"NAME\" TEXT," + // 1: NAME
                "\"VALUE\" TEXT," + // 2: VALUE
                "\"OFFER__ID\" INTEGER NOT NULL );"); // 3: OFFER_ID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PARAM_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ParamDB entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String NAME = entity.getNAME();
        if (NAME != null) {
            stmt.bindString(2, NAME);
        }
 
        String VALUE = entity.getVALUE();
        if (VALUE != null) {
            stmt.bindString(3, VALUE);
        }
        stmt.bindLong(4, entity.getOFFER_ID());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ParamDB entity) {
        stmt.clearBindings();
 
        Long ID = entity.getID();
        if (ID != null) {
            stmt.bindLong(1, ID);
        }
 
        String NAME = entity.getNAME();
        if (NAME != null) {
            stmt.bindString(2, NAME);
        }
 
        String VALUE = entity.getVALUE();
        if (VALUE != null) {
            stmt.bindString(3, VALUE);
        }
        stmt.bindLong(4, entity.getOFFER_ID());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ParamDB readEntity(Cursor cursor, int offset) {
        ParamDB entity = new ParamDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // ID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // NAME
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // VALUE
            cursor.getLong(offset + 3) // OFFER_ID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ParamDB entity, int offset) {
        entity.setID(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNAME(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVALUE(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setOFFER_ID(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ParamDB entity, long rowId) {
        entity.setID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ParamDB entity) {
        if(entity != null) {
            return entity.getID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ParamDB entity) {
        return entity.getID() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "mParamsList" to-many relationship of OfferDB. */
    public List<ParamDB> _queryOfferDB_MParamsList(Long OFFER_ID) {
        synchronized (this) {
            if (offerDB_MParamsListQuery == null) {
                QueryBuilder<ParamDB> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.OFFER_ID.eq(null));
                offerDB_MParamsListQuery = queryBuilder.build();
            }
        }
        Query<ParamDB> query = offerDB_MParamsListQuery.forCurrentThread();
        query.setParameter(0, OFFER_ID);
        return query.list();
    }

}
